### ISSUE TITLE
Add Prettier

### ISSUE THREAD

**Issue by MoonTahoe** [HighFivesFoundation/application-api#7]
We want to make sure all of our code looks the same. We need a prettier configuration for this project, and we need to make sure that configuration runs on all of the code files automatically.

- [ ] Create Prettier configuration
- [ ] Automate Prettier configuration

**Comment by MxOliver** [comment]
I'd like to work on this issue if it's still open!

**Comment by eveporcello** [comment]
That would be awesome! It’s all yours. Thanks!

**Comment by MoonTahoe** [comment]
@MxOliver I invited you to our backend team. Once you accept the invitation you can assign this issue to yourself.

**Comment by eveporcello** [comment]
Thank you @MxOliver!! So grateful for the time that you spent on this!!
